# Generated by Django 4.2.15 on 2024-08-17 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=0, max_length=100)),
                ('matricula', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='', max_length=50)),
                ('descricao', models.TextField(default='', max_length=240)),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('status', models.CharField(choices=[('1', 'Em Análise'), ('2', 'Aceito'), ('3', 'Em Diagnóstico'), ('4', 'Equipamento em conserto'), ('5', 'Aguardando peça'), ('6', 'Fechado sem resolução'), ('7', 'Resolvido'), ('8', 'Recusado')], max_length=30)),
                ('bolsistas', models.ManyToManyField(to='gambiarra.bolsista')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(default=0, max_length=30)),
                ('descricao', models.CharField(default=0, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de publicação')),
                ('id_autor', models.IntegerField(default=0)),
                ('eh_professor', models.BooleanField(default=True)),
                ('texto', models.TextField(default=0, max_length=240)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gambiarra.chamado')),
            ],
        ),
        migrations.AddField(
            model_name='chamado',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gambiarra.item'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField(default=0, max_length=240)),
                ('nota', models.IntegerField()),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gambiarra.chamado')),
            ],
        ),
        migrations.CreateModel(
            name='Alteracao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('1', 'Em Análise'), ('2', 'Aceito'), ('3', 'Em Diagnóstico'), ('4', 'Equipamento em conserto'), ('5', 'Aguardando peça'), ('6', 'Fechado sem resolução'), ('7', 'Resolvido'), ('8', 'Recusado')], max_length=30)),
                ('data_alteracao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de modificação')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gambiarra.chamado')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
