# Generated by Django 4.2.15 on 2024-12-13 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=50)),
                ('descricao', models.TextField(default='', max_length=240)),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('status', models.CharField(choices=[('1', 'Em Análise'), ('2', 'Aceito'), ('3', 'Em Diagnóstico'), ('4', 'Equipamento em conserto'), ('5', 'Aguardando peça'), ('6', 'Fechado sem resolução'), ('7', 'Resolvido'), ('8', 'Recusado')], default='1', max_length=30)),
                ('bolsistas', models.ManyToManyField(blank=True, null=True, related_name='chamados_bolsista', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chamados_cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(default='', max_length=30)),
                ('diagnostico', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de publicação')),
                ('texto', models.CharField(default='', max_length=240)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gambiarra.chamado')),
            ],
        ),
        migrations.AddField(
            model_name='chamado',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gambiarra.item'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chamados_professor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(default='', max_length=240)),
                ('nota', models.IntegerField()),
                ('chamado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gambiarra.chamado')),
            ],
        ),
        migrations.CreateModel(
            name='Alteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Em Análise'), ('2', 'Aceito'), ('3', 'Em Diagnóstico'), ('4', 'Equipamento em conserto'), ('5', 'Aguardando peça'), ('6', 'Fechado sem resolução'), ('7', 'Resolvido'), ('8', 'Recusado')], max_length=30)),
                ('data_alteracao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de modificação')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gambiarra.chamado')),
            ],
        ),
        migrations.CreateModel(
            name='Acessorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gambiarra.item')),
            ],
        ),
    ]
