# Generated by Django 4.2.15 on 2025-02-03 21:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gambiarra', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acessorio',
            options={'verbose_name_plural': 'Acessórios'},
        ),
        migrations.AlterModelOptions(
            name='alteracao',
            options={'verbose_name_plural': 'Alterações'},
        ),
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterModelOptions(
            name='mensagem',
            options={'verbose_name_plural': 'Mensagens'},
        ),
        migrations.AlterField(
            model_name='chamado',
            name='bolsistas',
            field=models.ManyToManyField(blank=True, related_name='chamados_bolsista', to=settings.AUTH_USER_MODEL),
        ),
    ]
