# Generated by Django 4.2.15 on 2024-08-19 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gambiarra', '0002_chamado_cliente_alter_chamado_professor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='descricao',
            new_name='problema',
        ),
        migrations.AlterField(
            model_name='chamado',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chamados_cliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
