# Generated by Django 4.2.15 on 2024-08-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gambiarra', '0003_rename_descricao_item_problema_alter_chamado_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('1', 'Em Análise'), ('2', 'Aceito'), ('3', 'Em Diagnóstico'), ('4', 'Equipamento em conserto'), ('5', 'Aguardando peça'), ('6', 'Fechado sem resolução'), ('7', 'Resolvido'), ('8', 'Recusado')], default='1', max_length=30),
        ),
    ]
