# Generated by Django 4.2.15 on 2024-08-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gambiarra', '0005_remove_alteracao_professor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsista',
            name='foto_perfil',
            field=models.ImageField(default=0, upload_to='Bolsista'),
        ),
    ]
