# Generated by Django 4.2.15 on 2024-08-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gambiarra', '0008_merge_20240828_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='texto',
            field=models.TextField(default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='bolsista',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='Bolsista'),
        ),
        migrations.AlterField(
            model_name='bolsista',
            name='matricula',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bolsista',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='modelo',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='problema',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='texto',
            field=models.TextField(default='', max_length=240),
        ),
    ]
