# Generated by Django 4.2.15 on 2024-09-08 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gambiarra', '0011_alter_chamado_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='chamado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gambiarra.chamado'),
        ),
        migrations.AlterField(
            model_name='bolsista',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='../media/Bolsista/perfil_teste.jpg', null=True, upload_to='Bolsista'),
        ),
    ]
