# Generated by Django 4.2.15 on 2024-11-27 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gambiarra', '0013_alter_bolsista_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='problema',
        ),
        migrations.AddField(
            model_name='item',
            name='diagnostico',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Acessorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gambiarra.item')),
            ],
        ),
    ]
