version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/gamb-front"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
    labels:
      - "dependabot"

  - package-ecosystem: "pip"
    directory: "/gamb-back"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
    labels:
      - "dependabot"