services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  web:
    image: liviaavs/gamb-back:latest
    container_name: gambdrf
    command: >
      bash -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py populate_grupos &&
      python manage.py populate_usuarios_nos &&
      python manage.py populate_models &&
      python manage.py runserver 0.0.0.0:8000"

    ports:
      - "8000:8000"
    depends_on:
      - db  
    env_file:
      - .env

  db:
    image: postgres:13-alpine
    container_name: gambdevdb
    volumes:
      - postgres_data:/var/lib/postgresql/data/   
    env_file:
      - .env 
    ports:
      - "5432:5432"

 
volumes:
  postgres_data:

