import {
	ArchiveIcon,
	ArticleIcon,
	BarcodeIcon,
	BellIcon,
	BellRingingIcon,
	CalendarIcon,
	CameraIcon,
	CaretCircleDownIcon,
	CaretLeftIcon,
	CaretRightIcon,
	ChatCircleIcon,
	ChatsCircleIcon,
	CheckCircleIcon,
	CheckIcon,
	ChecksIcon,
	CircleIcon,
	ClipboardIcon,
	ClockClockwiseIcon,
	EnvelopeIcon,
	EyeClosedIcon,
	EyeIcon,
	EyeSlashIcon,
	FileTextIcon,
	FlowerIcon,
	GearIcon,
	GreaterThanIcon,
	HeartIcon,
	HouseIcon,
	HouseLineIcon,
	InfoIcon,
	LegoIcon,
	ListIcon,
	ListMagnifyingGlassIcon,
	LockIcon,
	MapPinIcon,
	MinusIcon,
	MusicNoteIcon,
	NotePencilIcon,
	PauseIcon,
	PlayIcon,
	PlusCircleIcon,
	PlusIcon,
	ShoppingCartIcon,
	SimCardIcon,
	SkipBackCircleIcon,
	StarIcon,
	TextTIcon,
	TrashIcon,
	UserCircleCheckIcon,
	UserCircleGearIcon,
	UserCircleMinusIcon,
	UserCirclePlusIcon,
	UserIcon,
	UsersFourIcon,
	WarningDiamondIcon,
	WarningIcon,
	XCircleIcon,
	XIcon,
} from "@phosphor-icons/react";
import { GambIconProps } from "../../interfaces/componentes/iGambIcon";
import { cloneElement } from "react";

const iconComponents: Record<string, React.JSX.Element> = {
	house: <HouseIcon />,
	heart: <HeartIcon />,
	user: <UserIcon />,
	gear: <GearIcon />,
	bell: <BellIcon />,
	star: <StarIcon />,
	musicNote: <MusicNoteIcon />,
	trash: <TrashIcon />,
	lock: <LockIcon />,
	camera: <CameraIcon />,
	shopping_cart: <ShoppingCartIcon />,
	calendar: <CalendarIcon />,
	clipboard: <ClipboardIcon />,
	play: <PlayIcon />,
	pause: <PauseIcon />,
	plus_circle: <PlusCircleIcon />,
	plus: <PlusIcon />,
	minus: <MinusIcon />,
	seta_direita: <CaretRightIcon />,
	seta_esquerda: <CaretLeftIcon />,
	checkcircle: <CheckCircleIcon />,
	info: <InfoIcon weight="fill" />,
	warning: <WarningDiamondIcon />,
	danger: <WarningIcon />,
	close: <XIcon />,
	seta_baixo: <CaretCircleDownIcon />,
	arquivo: <FileTextIcon />,
	lego: <LegoIcon />,
	list: <ListIcon />,
	usercirclegear: <UserCircleGearIcon  weight="thin" />,
	usercircleplus: <UserCirclePlusIcon weight="thin" />,
	usercirclecheck: <UserCircleCheckIcon weight="thin" />,
	usercircleminus: <UserCircleMinusIcon weight="thin" />,
	greaterthan: <GreaterThanIcon weight="bold" />,
	greenhouse: <HouseLineIcon weight="fill" />,
	envelope: <EnvelopeIcon />,
	pin: <MapPinIcon />,
	chat: <ChatCircleIcon />,
	bellringing: <BellRingingIcon />,
	circle: <CircleIcon />,
	eyeclose: <EyeClosedIcon />,
	eyeopen: <EyeIcon />,
	eyeslash: <EyeSlashIcon />,
	checks: <ChecksIcon />,
	xcircle: <XCircleIcon />,
	archive: <ArchiveIcon />,
	x: <XIcon />,
	check: <ChecksIcon />,
	search: <ListMagnifyingGlassIcon />,
	back: <SkipBackCircleIcon />,
	flower: <FlowerIcon />,

	fillcircle: <CircleIcon weight="fill" />,
	text: <TextTIcon />,
	simcard: <SimCardIcon />,
	article: <ArticleIcon />,
	barcode: <BarcodeIcon />,
	usersfour: <UsersFourIcon />,
	note_pencil: <NotePencilIcon />,
	onecheck: <CheckIcon />,
	chatfill: <ChatsCircleIcon />,
	clock: <ClockClockwiseIcon />,
	send: <ChatCircleIcon />,
};

export default function Icon(props: GambIconProps): React.JSX.Element {
	const { icon, size, color, className } = props;

	// Verifica se o ícone existe no mapeamento e retorna ele
	const IconComponent = iconComponents[icon.toLowerCase()];

	return (
		<>
			{IconComponent &&
				cloneElement(IconComponent, {
					size: size || 16,
					color,
					className,
				})}
		</>
	);
}
