import {
	House,
	Heart,
	User,
	Gear,
	Bell,
	Star,
	MusicNote,
	Trash,
	Lock,
	Camera,
	ShoppingCart,
	Calendar,
	Clipboard,
	Play,
	Pause,
	Plus,
	Minus,
	CaretRight,
	CaretLeft,
	CheckCircle,
	Info,
	WarningDiamond,
	Warning,
	X,
	CaretCircleDown,
	FileText,
	Lego,
	List,
	Envelope,
	UserCircleGear,
	UserCirclePlus,
	UserCircleCheck,
	UserCircleMinus,
	GreaterThan,
	HouseLine,
	MapPin,
	ChatCircle,
	BellRinging,
	Circle,
	Eye,
	EyeSlash,
	EyeClosed,
	Checks,
	XCircle,
	Archive,
	TextAlignCenter,
} from "@phosphor-icons/react";
import { GambIconProps } from "../../interfaces/componentes/iGambIcon";
import { cloneElement } from "react";
 
const iconComponents: { [key: string]: JSX.Element } = {
	house: <House />,
	heart: <Heart />,
	user: <User />,
	gear: <Gear />,
	bell: <Bell />,
	star: <Star />,
	musicNote: <MusicNote />,
	trash: <Trash />,
	lock: <Lock />,
	camera: <Camera />,
	shopping_cart: <ShoppingCart />,
	calendar: <Calendar />,
	clipboard: <Clipboard />,
	play: <Play />,
	pause: <Pause />,
	plus: <Plus />,
	minus: <Minus />,
	seta_direita: <CaretRight />,
	seta_esquerda: <CaretLeft />,
	checkcircle: <CheckCircle />,
	info: <Info weight="fill" />,
	warning: <WarningDiamond />,
	danger: <Warning />,
	close: <X />,
	seta_baixo: <CaretCircleDown />,
	arquivo: <FileText />,
	lego: <Lego />,
	list: <List />,
	usercirclegear: <UserCircleGear weight="thin" />,
	usercircleplus: <UserCirclePlus weight="thin" />,
	usercirclecheck: <UserCircleCheck weight="thin" />,
	usercircleminus: <UserCircleMinus weight="thin" />,
	greaterthan: <GreaterThan weight="bold" />,
	greenhouse: <HouseLine weight="fill" />,
	envelope: <Envelope />,
	pin: <MapPin />,
	chat: <ChatCircle />,
	bellringing: <BellRinging />,
	circle: <Circle />,
	eyeclose: <EyeClosed />,
	eyeopen: <Eye />,
	eyeslash: <EyeSlash />,
	checks: <Checks />,
	xcircle: <XCircle />,
	archive: <Archive />,
	texto: <TextAlignCenter />,
	x: <X />,
	check: <Checks />,
};

export default function Icon(props: GambIconProps): JSX.Element {
	const { icon, size, color, className } = props;

	// Verifica se o ícone existe no mapeamento e retorna ele
	const IconComponent = iconComponents[icon.toLowerCase()];

	return (
		<>
			{IconComponent &&
				cloneElement(IconComponent, {
					size: size || 16,
					color,
					className,
				})}
		</>
	);
}
