# Generated by Django 4.2.15 on 2024-08-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('1', 'Aluno'), ('2', 'Externo'), ('3', 'Servidor'), ('4', 'Professor')], default=None, max_length=20),
        ),
    ]
