# Generated by Django 4.2.15 on 2024-08-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('1', 'Aluno'), ('2', 'Externo'), ('3', 'Servidor'), ('4', 'Professor')], max_length=20, null=True),
        ),
    ]
