# Generated by Django 4.2.15 on 2024-09-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='Usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('1', 'Aluno'), ('2', 'Externo'), ('3', 'Servidor'), ('4', 'Professor')], default='4', max_length=20),
        ),
    ]
