# Generated by Django 4.2.15 on 2024-09-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_foto_perfil_alter_user_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='../media/Padrao/perfil_default.png', null=True, upload_to='Usuario'),
        ),
    ]
