# Generated by Django 4.1.7 on 2024-07-16 23:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('status', models.CharField(choices=[('Em Análise', ' O problema está sendo avaliado. '), ('Aceito', 'Um professor aceitou o seu chamado, traga seu equipamento!'), ('Em Diagnóstico', 'A causa raiz está sendo identificada.'), ('Equipamento em conserto', 'O reparo está em andamento.'), ('Aguardando peça', 'Estamos esperando por uma peça de reposição.'), ('Fechado sem resolução', 'O problema foi encerrado sem solução.'), ('Resolvido', 'O problema foi corrigido com sucesso.'), ('Recusado', 'O chamado foi recusado.')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(default=0, max_length=11)),
                ('matricula', models.CharField(default=0, max_length=20)),
                ('nome', models.CharField(default=0, max_length=30)),
                ('email', models.EmailField(default=0, max_length=30)),
                ('senha', models.CharField(default=0, max_length=30)),
                ('telefone', models.CharField(default=0, max_length=15)),
                ('foto_perfil', models.ImageField(default=0, upload_to='../media')),
                ('caracteristica', models.CharField(choices=[('AL', 'Aluno'), ('EX', 'Externo'), ('SE', 'Servidor')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(default=0, max_length=11)),
                ('matricula', models.CharField(default=0, max_length=20)),
                ('nome', models.CharField(default=0, max_length=30)),
                ('email', models.EmailField(default=0, max_length=30)),
                ('senha', models.CharField(default=0, max_length=30)),
                ('telefone', models.CharField(default=0, max_length=30)),
                ('foto_perfil', models.ImageField(default=0, upload_to='../media')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_envio', models.DateTimeField(default=datetime.datetime(2024, 7, 16, 23, 45, 40, 823436, tzinfo=datetime.timezone.utc), verbose_name='Data de publicação')),
                ('texto', models.TextField(default=0, max_length=240)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gambiarra.cliente')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gambiarra.chamado')),
            ],
        ),
        migrations.AddField(
            model_name='chamado',
            name='bolsistas',
            field=models.ManyToManyField(to='gambiarra.cliente'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gambiarra.professor'),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField(default=0, max_length=240)),
                ('nota', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('id_chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gambiarra.chamado')),
            ],
        ),
    ]
