# Generated by Django 4.1.7 on 2024-07-16 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gambiarra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='data_envio',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 16, 23, 45, 48, 799526, tzinfo=datetime.timezone.utc), verbose_name='Data de publicação'),
        ),
    ]
