# Generated by Django 4.1.7 on 2024-07-16 23:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gambiarra', '0003_alter_mensagem_data_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='data_envio',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de publicação'),
        ),
    ]
