# Generated by Django 4.1.7 on 2024-07-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gambiarra', '0004_alter_mensagem_data_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto_perfil',
            field=models.ImageField(default=0, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='foto_perfil',
            field=models.ImageField(default=0, upload_to='media'),
        ),
    ]
