# Generated by Django 4.2.15 on 2024-08-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gambiarra', '0005_remove_alteracao_professor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='texto',
            field=models.TextField(blank=True, default=None, max_length=240),
        ),
    ]
