# Generated by Django 4.1.7 on 2024-07-17 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gambiarra', '0005_alter_cliente_foto_perfil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='foto_perfil',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='foto_perfil',
        ),
    ]
