# Generated by Django 4.2.15 on 2024-08-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gambiarra', '0006_bolsista_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='bolsistas',
            field=models.ManyToManyField(blank=True, to='gambiarra.bolsista'),
        ),
    ]
