# Generated by Django 4.2.15 on 2024-08-28 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gambiarra', '0006_alter_mensagem_texto'),
        ('gambiarra', '0007_alter_chamado_bolsistas'),
    ]

    operations = [
    ]
