# Generated by Django 4.1.7 on 2024-07-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gambiarra', '0007_rename_id_chamado_avaliacao_chamado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='chamada',
            new_name='chamado',
        ),
        migrations.AlterField(
            model_name='alteracao',
            name='status',
            field=models.CharField(choices=[('Em Análise', ' O problema está sendo avaliado.'), ('Aceito', 'Um professor aceitou o seu chamado, traga seu equipamento!'), ('Em Diagnóstico', 'A causa raiz está sendo identificada.'), ('Equipamento em conserto', 'O reparo está em andamento.'), ('Aguardando peça', 'Estamos esperando por uma peça de reposição.'), ('Fechado sem resolução', 'O problema foi encerrado sem solução.'), ('Resolvido', 'O problema foi corrigido com sucesso.'), ('Recusado', 'O chamado foi recusado.')], max_length=30),
        ),
    ]
