# Generated by Django 4.1.7 on 2024-07-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gambiarra', '0008_rename_chamada_item_chamado_alter_alteracao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='descricao',
            field=models.TextField(default=0, max_length=240),
        ),
        migrations.AddField(
            model_name='chamado',
            name='titulo',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
