# Generated by Django 4.2.15 on 2024-09-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gambiarra', '0009_alter_avaliacao_texto_alter_bolsista_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='texto',
            field=models.CharField(default='', max_length=240),
        ),
    ]
