# Generated by Django 5.0.7 on 2024-08-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gambiarra', '0009_chamado_descricao_chamado_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alteracao',
            name='status',
            field=models.CharField(choices=[('1', 'Em Análise'), ('2', 'Aceito'), ('3', 'Em Diagnóstico'), ('4', 'Equipamento em conserto'), ('5', 'Aguardando peça'), ('6', 'Fechado sem resolução'), ('7', 'Resolvido'), ('8', 'Recusado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('1', 'Em Análise'), ('2', 'Aceito'), ('3', 'Em Diagnóstico'), ('4', 'Equipamento em conserto'), ('5', 'Aguardando peça'), ('6', 'Fechado sem resolução'), ('7', 'Resolvido'), ('8', 'Recusado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='caracteristica',
            field=models.CharField(choices=[('1', 'Aluno'), ('2', 'Externo'), ('3', 'Servidor')], max_length=2),
        ),
    ]
