# Generated by Django 4.2.15 on 2024-09-03 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gambiarra', '0010_alter_mensagem_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chamados_professor', to=settings.AUTH_USER_MODEL),
        ),
    ]
