# Generated by Django 4.2.15 on 2024-08-16 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gambiarra', '0011_alter_avaliacao_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='chamado',
        ),
        migrations.AddField(
            model_name='chamado',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gambiarra.item'),
        ),
    ]
