# Generated by Django 4.2.15 on 2024-09-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gambiarra', '0012_alter_avaliacao_chamado_alter_bolsista_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsista',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='../media/Padrao/perfil_default.png', null=True, upload_to='Bolsista'),
        ),
    ]
