# Generated by Django 4.2.15 on 2024-08-16 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gambiarra', '0012_remove_item_chamado_chamado_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gambiarra.item'),
        ),
    ]
