# Generated by Django 4.2.15 on 2024-08-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gambiarra', '0013_alter_chamado_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='descricao',
            field=models.TextField(default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='titulo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
