name: OWASP Dependency Check - Full Stack

on:
    push:
        branches: [309-0---configurar-owasp-dependency-check]
    pull_request:
        branches: [309-0---configurar-owasp-dependency-check]

jobs:
    dependency-check:
        name: Análise de Dependências - Frontend e Backend
        runs-on: ubuntu-latest

        steps:
            - name: Checkout do código
              uses: actions/checkout@v3

            - name: Instalar Java
              uses: actions/setup-java@v3
              with:
                  distribution: "temurin"
                  java-version: "17"

            - name: Instalar OWASP Dependency-Check
              run: |
                  wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
                  unzip dependency-check-8.4.0-release.zip -d dependency-check
                  sudo ln -s $PWD/dependency-check/bin/dependency-check.sh /usr/local/bin/dependency-check

            - name: Instalar dependências do gamb-back (Python/Django)
              run: |
                  python -m venv venv
                  source venv/bin/activate
                  pip install -r gamb-back/requirements.txt

            - name: Instalar dependências do gamb-front (React)
              run: |
                  cd gamb-front
                  npm install

            - name: Análise do Backend com OWASP Dependency-Check
              run: |
                  dependency-check --project "Django REST API" --scan gamb-back --format HTML --out reports-gamb-back

            - name: Análise do Frontend com OWASP Dependency-Check
              run: |
                  dependency-check --project "React Frontend" --scan gamb-front --format HTML --out reports-gamb-front

            - name: Upload dos relatórios
              uses: actions/upload-artifact@v4
              with:
                  name: dependency-check-reports
                  path: |
                      reports-gamb-back
                      reports-gamb-front
