name: CI-back

on:
  push:
    branches: ["*"]
    paths:
      - "gamb-back/gambiarra/**"
      - ".github/workflows/CI-back.yml"

jobs:
  back:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DEBUG: ${{ secrets.DEBUG }}
      DJANGO_LOGLEVEL: ${{ secrets.DJANGO_LOGLEVEL }}
      DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
      DATABASE_ENGINE: ${{ secrets.DATABASE_ENGINE }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USER: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}

    steps:
      - uses: actions/checkout@v4

      # Etapa 1: Inicia os containers em background
      - name: Start Docker containers
        run: |
          cd gamb-back
          docker compose up -d
          docker compose ps  # Verifica status

      # Etapa 2: Instala dependências Python (para Flake8/Black)
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      # Etapa 3: Executa testes Django
      - name: Run Django tests
        run: |
          cd gamb-back
          docker compose exec -T gambdrf python manage.py test

      # Etapa 4: Verificação de código
      - name: Run Flake8
        run: |
          cd gamb-back
          flake8 . --count --show-source --statistics

      - name: Run Black
        run: |
          cd gamb-back
          black . --check

      # Etapa 5: Geração do diagrama
      - name: Install Graphviz and generate diagram
        run: |
          sudo apt update
          sudo apt install graphviz -y
          cd gamb-back
          TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
          docker compose exec -T gambdrf python manage.py graph_models gambiarra -o diagrams/gambiarra_$TIMESTAMP.png

      # Etapa 6: Upload do diagrama
      - name: Upload diagram artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: gambiarra_diagram
          path: gamb-back/diagrams/**

      # Etapa FINAL: Limpeza dos containers (sempre executada)
      - name: Cleanup Docker containers
        if: always()  # Executa mesmo se etapas anteriores falharem
        run: |
          cd gamb-back
          docker compose down --volumes --remove-orphans