name: CI-Front

on:
    push:
        branches: ["*"]
        paths:
            - "gamb-front/**"
            - ".github/workflows/CI-front.yml"

    pull_request:
        branches: ["*"]
        paths:
            - "gamb-front/**"
            - ".github/workflows/CI-front.yml"

jobs:
             
    front:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4.2.2
            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 22.15.0

            - name: Install dependencies
              run: |
                  cd gamb-front
                  npm install

            - name: Lint
              run: |
                    cd gamb-front
                    npm run lint

            - name: Cypress run
              uses: cypress-io/github-action@v6
              env:
                VITE_API_URL: "http://localhost:8000/api/v1/"
                VITE_HOST: "localhost"
              with:
                  build: yarn build
                  start: yarn preview
                  working-directory: gamb-front


          