name: CD Pipeline

on:
    push:
        branches: ["298-0---implementar-cd-de-deploy-do-projeto"]
    pull_request:
        branches: ["298-0---implementar-cd-de-deploy-do-projeto"]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set Up SSH Key
              shell: bash
              run: |
                  echo "${{ secrets.EC2_KEY }}" > ~/DjangoCDKey.pem
                  chmod 400 ~/DjangoCDKey.pem

            - name: Deploy Code
              shell: bash
              run: |
                  # Copy all project files to the EC2 instance
                  scp -o StrictHostKeyChecking=no -i ~/DjangoCDKey.pem * ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/Django_Project/

                  # SSH into the EC2 instance and deploy
                  ssh -o StrictHostKeyChecking=no -i ~/DjangoCDKey.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
                    cd /home/${{ secrets.EC2_USER }}/Django_Project &&
                    docker-compose up --build -d
                  "

#  - name: Conectar ao servidor remoto
#               run: |
#                 ssh -tt -i 'gamb-keys.pem' ubuntu@52.22.187.150 <<EOF
#                   ls
#                    cd gambiarra/gamb-back/
#                    echo "DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY" > .env
#                    echo "DEBUG=$DEBUG" >> .env
#                    echo "DJANGO_LOGLEVEL=$DJANGO_LOGLEVEL" >> .env
#                    echo "DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS" >> .env
#                    echo "DATABASE_ENGINE=$DATABASE_ENGINE" >> .env
#                    echo "DATABASE_NAME=$DATABASE_NAME" >> .env
#                    echo "DATABASE_USERNAME=$DATABASE_USERNAME" >> .env
#                    echo "DATABASE_PASSWORD=$DATABASE_PASSWORD" >> .env
#                    echo "DATABASE_HOST=$DATABASE_HOST" >> .env
#                    echo "DATABASE_PORT=$DATABASE_PORT" >> .env
#                 EOF
