name: Django CD

on:
  push:
    branches: ["298-0---implementar-cd-de-deploy-do-projeto"]
  pull_request:
    branches: ["298-0---implementar-cd-de-deploy-do-projeto"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DEBUG: ${{ secrets.DEBUG }}
      DJANGO_LOGLEVEL: ${{ secrets.DJANGO_LOGLEVEL }}
      DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
      DATABASE_ENGINE: ${{ secrets.DATABASE_ENGINE }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}

    steps:
      - uses: actions/checkout@v4

      - name: Adicionar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.gamb-keys-back }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan ec2-52-22-187-150 >> ~/.ssh/known_hosts

      - name: Conectar ao servidor remoto
        run: ssh -i ~/.ssh/id_rsa ubuntu@ec2-52-22-187-150 "echo 'Conectado com sucesso!'"
      
      - name: Criando arquivo .env
        run: |
          cd gambiarra/
          cd gamb-back/
          pwd
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" > .env
          echo "DEBUG=${{ secrets.DEBUG }}" >> .env
          echo "DJANGO_LOGLEVEL=${{ secrets.DJANGO_LOGLEVEL }}" >> .env
          echo "DJANGO_ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }}" >> .env
          echo "DATABASE_ENGINE=${{ secrets.DATABASE_ENGINE }}" >> .env
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env
          echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env