name: Django CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
jobs:
  test:
    runs-on: ubuntu-latest

    env: 
      SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DEBUG: ${{ vars.DEBUG }}
      DJANGO_LOGLEVEL: ${{ vars.DJANGO_LOGLEVEL }}
      DJANGO_ALLOWED_HOSTS: ${{ vars.DJANGO_ALLOWED_HOSTS }}
      DATABASE_ENGINE: ${{ vars.DATABASE_ENGINE }}
      DATABASE_NAME: ${{ vars.DATABASE_NAME }}
      DATABASE_USERNAME: ${{ vars.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ vars.DATABASE_PASSWORD }}
      DATABASE_HOST: ${{ vars.DATABASE_HOST }}
      DATABASE_PORT: ${{ vars.DATABASE_PORT }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Test env
        run: | 
          echo "SECRET_KEY is set: ${SECRET_KEY:+yes}"
          echo "DEBUG= ${{ vars.DEBUG }}"
       

      - name: Install dependencies
        run: |
          cd gamb-back
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        env:
          DJANGO_SETTINGS_MODULE: mysite.settings
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DATABASE_URL: postgres://postgres:postgres@postgres:5432/github_actions
        run: |
          cd gamb-back
          python manage.py migrate

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: mysite.settings
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: |
          cd gamb-back
          python manage.py test
