name: Django CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DEBUG: ${{ secrets.DEBUG }}
      DJANGO_LOGLEVEL: ${{ secrets.DJANGO_LOGLEVEL }}
      DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
      DATABASE_ENGINE: ${{ secrets.DATABASE_ENGINE }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}

    steps:
      - uses: actions/checkout@v4

      # Configura o Docker Buildx
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Rodar os containers Docker (web + db + redis)
      - name: Run docker-compose up
        run: |
          cd gamb-back
          docker-compose -f docker-compose.local.yml up --build -d
        # O parâmetro -d roda os containers em segundo plano

      # Esperar o banco de dados ficar pronto antes de tentar conectar
      - name: Wait for DB to be ready
        run: |
          cd gamb-back
          docker exec -t gambdevdb pg_isready -U postgres
        # Gambdevdb é o nome do seu contêiner PostgreSQL, conforme o docker-compose.yml

      # Rodar migrações dentro do contêiner do Django
      - name: Run migrations inside Docker container
        run: |
          cd gamb-back
          docker exec -t gambdrf python manage.py migrate
        # Gambdrf é o nome do seu contêiner Django, conforme o docker-compose.yml

      # Rodar testes dentro do contêiner do Django
      - name: Run tests inside Docker container
        run: |
          cd gamb-back
          docker exec -t gambdrf python manage.py test
        # Gambdrf é o nome do seu contêiner Django, conforme o docker-compose.yml

      # Desligar os containers após a execução dos testes
      - name: Shut down Docker containers
        run: |
          cd gamb-back
          docker-compose -f docker-compose.local.yml down
