name: Trivy Security Scan

on:
  push:
    branches: ["*"]
    paths:
      - "gamb-front/package.json"
      - "gamb-back/requirements.txt"
  pull_request:
    branches: ["*"]
    paths:
      - "gamb-front/package.json"
      - "gamb-back/requirements.txt"

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    name: Run Trivy

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      - name: Scan Node.js dependencies (gamb-front)
        run: |
          trivy fs --scanners vuln --exit-code 1 --severity HIGH,CRITICAL ./gamb-front

      - name: Scan Python dependencies (gamb-back)
        run: |
          trivy fs --scanners vuln --exit-code 1 --severity HIGH,CRITICAL ./gamb-back
name: Packj OWASP Check
on: 
  push:
    branches: ["*"]
    paths:
      - "gamb-front/package.json"
      - "gamb-back/requirements.txt"
      - ".github/workflows/OWASP-check.yml"
  pull_request:
    branches: ["*"]
    paths:
      - "gamb-front/package.json"
      - "gamb-back/requirements.txt"
      - ".github/workflows/OWASP-check.yml"

jobs:
    check-owasp:
      runs-on: ubuntu-latest
      steps:

      # Audit 
      - name: Audit dependencies
        uses: ossillate-inc/packj-github-action@v0.0.11-beta
        with:
          # TODO: replace with your dependency files in the repo
          DEPENDENCY_FILES: pypi:requirements.txt,npm:package.json
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}