name: Packj OWASP Check
on: 
  push:
    branches: ["*"]
    paths:
      - "gamb-front/package.json"
      - "gamb-back/requirements.txt"
      - ".github/workflows/OWASP-check.yml"
  pull_request:
    branches: ["*"]
    paths:
      - "gamb-front/package.json"
      - "gamb-back/requirements.txt"
      - ".github/workflows/OWASP-check.yml"

jobs:
    check-owasp:
      runs-on: ubuntu-latest
      steps:

      # Audit 
      - name: Audit dependencies
        uses: ossillate-inc/packj-github-action@v0.0.11-beta
        with:
          # TODO: replace with your dependency files in the repo
          DEPENDENCY_FILES: pypi:requirements.txt,npm:package.json
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}